name: Test SNAPSHOT Plugin from GitHub Packages

on:
  workflow_run:
    workflows: ["Publish SNAPSHOT to GitHub Packages"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Configure GitHub Packages Resolver and Credentials
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.sbt/1.0
          echo "resolvers += \"GitHub Packages\" at \"https://maven.pkg.github.com/Sahilpatkar/sbt-flink-assembly-optimizer-plugin\"" >> project/plugins.sbt
          echo "credentials += Credentials(\"GitHub Package Registry\", \"maven.pkg.github.com\", \"$GITHUB_ACTOR\", \"$GITHUB_TOKEN\")" >> ~/.sbt/1.0/global.sbt
          echo "addSbtPlugin(\"com.sp\" % \"sbt-flink-assembly-optimizer-plugin\" % \"0.2-SNAPSHOT\")" >> project/plugins.sbt

      - name: Run tests
        run: ./plugin_test.sh
