name: Test SNAPSHOT Plugin from GitHub Packages

on:
  workflow_run:
    workflows: ["Publish SNAPSHOT to GitHub Packages"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Add GitHub Packages Resolver for SNAPSHOT
        run: |
          echo "resolvers += \"GitHub Packages\" at \"https://maven.pkg.github.com/Sahilpatkar/sbt-flink-assembly-optimizer-plugin\"" >> project/plugins.sbt
          echo "addSbtPlugin(\"com.sp\" % \"sbt-flink-assembly-optimizer-plugin\" % \"0.2-SNAPSHOT\")" >> project/plugins.sbt

      - name: Run tests
        run: ./plugin_test.sh
