name: Publish SNAPSHOT to GitHub Packages

on:
  push:
    branches:
      - main  # Triggers on every push to the main branch for SNAPSHOT releases

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish SNAPSHOT to GitHub Packages
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sbt publish

permissions:
  contents: write
  packages: write
